# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Create Release

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v9.0.20
        with:
          minor-wording: 'feat'
          patch-wording: 'patch,fix,chore'
      - name: Build
        run: npm run build
      - name: Create Archive
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'plugin.zip'
          path: './plugin'
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.package-version.outputs.current-version}}
          artifacts: "plugin.zip"
          generateReleaseNotes: true
          allowUpdates: true

